### ISSUE TITLE
Sort by date rather than by citation count

### ISSUE THREAD

**Issue by jwjeffr** [ezefranca/scholarly_publications#1]
Hello!

I have a case where I would like to build a list of the N most recent publications for an author. On someone's Google scholar page, there's an option to sort by date rather than by citation count. Is it possible to add this feature to this application?

Thanks!

PS: I've been looking for an application like this for months now so this is super convenient 😊

**Comment by jwjeffr** [comment]
Will try to implement this myself as well at https://github.com/jwjeffr/scholarly_publications

**Comment by ezefranca** [comment]
Closing since @jwjeffr implemented himself.
